### PR TITLE
Convert AOT generation code to library + simple Unity editor AOT tool

### PR DESCRIPTION
**Pull request by zvinless**
This is primarily to facilitate a more streamlined workflow for AOT generation in Unity.

Main changes:
* Removes Roslyn dependencies in favor of manually formatting the generated script (lots of `\t` 😄) so that there will be fewer .dlls for Unity projects. I don't think they're worth it _just_ for formatting, but I'd be fine reverting this change since the Roslyn stuff should work with newer versions of the Unity editor.
* Changes `Ceras.AotGenerator` to output a .dll instead of an .exe, so that the .dll can be dropped into Unity
    * The library has a single public function that takes an `IEnumerable<Assembly>` and a `StringBuilder` for the code output. Currently, it's the caller's responsibility to prepare those.
* Adds a `Ceras.AotGeneratorApp` project that does output an executable, which should maintain the existing functionality.

Other things to note:
* This removes custom Unity assembly resolution code, since this shouldn't be necessary (hopefully) if executing the code generation from within Unity. If using the executable and pointing it to a mono build, that build _should_ contain all the necessary .dlls, and they should get resolved by default. It's definitely possible that I'm missing something, though.
* I have no attachments to any project/file/class/function names 😛. They can be whatever.

TODO:
* Include a Unity editor script somewhere so that users don't need to write their own. The library interface is simple (one public function), but if a script is supplied, it will need to be configurable so that users can decide where to output the resulting .cs file.
* Be able to generate a unity package for use with the Package Manager (maybe)

### CODE REVIEW

**Comment by rikimaru0345** [comment]
Hey, thanks for doing this! Most people are using Unity anyway (from what I can tell there's nobody who's compiling for an Aot platform that is not IL2CPP).

I've added a few comments to the top of Program.cs of the generator in one of my latest commits.
There is a section inside that talks about a potential issue with version tolerance that could be relevant here (not sure yet).

todo for myself when this is ready:

- update [wiki entry](https://github.com/rikimaru0345/Ceras/wiki/Unity-IL2CPP-(iOS-and-AOT))
- fix appveyor build script
- possibly add xml documentation

**Comment by zvinless** [comment]
I don't _think_ the version tolerance will be relevant to these changes in particular; the goal of this is to streamline workflow for AOT code generation. The actual inner workings of serialization/deserialization that uses the generated output shouldn't change.

I'll need to familiarize myself more with those inner workings, though, because version tolerance is important!

**Comment by rikimaru0345** [comment]
> I don't think the version tolerance will be relevant to these changes in particular; the goal of this is to streamline workflow for AOT code generation in Unity. The actual inner workings of serialization/deserialization that uses the generated output shouldn't change.

Ah yes, for the workflow improvement alone my comment isn't really relevant.
I was already thinking about some further steps/ideas and got things mixed up, sorry about that!

> I'll need to familiarize myself more with those inner workings, though, because version tolerance is important!

Sounds good, don't hesitate to ask if something is unclear!! :smile: 
Don't feel obligated to fix this yourself though.

Right now `CerasSerializer` will throw an exception when you use the `AotMode` and `VersionTolerance` settings at the same time.
I take it you definitely want to use both features at the same time though, right?

I'll open an issue to track that as a feature request then.

**Comment by zvinless** [comment]
Eventually, yeah. Right now it's not an immediate concern since I'm actually in a situation where I don't need version tolerance, but it'll be absolutely necessary later on. Thanks!

**Comment by rikimaru0345** [comment]
See #52 for a detailed explanation of why AotMode+VersionTolerance is not straightforward and possible solutions.

**Comment by zvinless** [comment]
I added a minimal editor script, though I'm not sure if it should be in its own project. Here are some thoughts:

I initially made the class visibility of `GeneratedFormatters` configurable as mentioned in the comments, but it seemed like one more thing to worry about without any real benefit. Since the `GeneratedFormatters.UseFormatters()` function [_is_ called by the end user](https://github.com/rikimaru0345/Ceras/wiki/Unity-IL2CPP-(iOS-and-AOT)#4-use-the-formatters), I think it's clearer to make it public, so I personally prefer convention to configuration in this case (let me know if you disagree; very easy to change!).

There are a few routes possible for configuring the editor script. I think it's necessary to have at least a configurable output file path, which could be any of:
* Have users edit a C# variable (they're programmers after all, right? 😛). This could make use of a partial function so the "config" could be a separate file and Ceras updates wouldn't overwrite it.
* Create a ScriptableObject asset for configuration, and potentially a "Ceras Window" or something. This seems like it might be overkill for 1 or 2 config options, but would make sense for a larger-scale Unity integration (think default serializer config, automatic AOT generation config, etc).
* Some other simple text file configuration format

There's also a variety of options for making Ceras easily available to Unity users. Right now I'm building from source and copying and pasting .dll files into my Unity project's Plugins directory:
* System.Buffers
* System.Runtime.CompilerServices.Unsafe
* Ceras
* Ceras.AotGenerator (I mark this as Editor only in the inspector)

and then copying and pasting the .cs files:
* Extensions.cs
* Editor/EditorExtensions.cs

Issues here:
1. The System .dll files, while not present by default in the Unity editor, could already exist in the project (and could moreover be different versions than what Ceras uses). Since they aren't isolated via namespacing, this could cause collisions. I'm not sure what the best way to deal with that is since Unity doesn't have any sort of dependency management system.
2. Building from source and copying and pasting is not so user-friendly. Creating a Unity package with all relevant files would probably be best. I'm not sure how much maintenance is involved with that, but I can look into it. This could either include .dlls or the source scripts.

**Comment by rikimaru0345** [comment]
> I think it's clearer to make it public, so I personally prefer convention to configuration in this case (let me know if you disagree; very easy to change!).

Should be fine!

> There are a few routes possible for configuring the editor script. I think it's necessary to have at least a configurable output file path, which could be any of: ...

I agree that there must be a way to configure it. (even if not right now, if its just the path, then yes, maybe we can get away with no settings, but not for very long)

But how? That's difficult. 

If the script is there in source-code form I think (as a user) I'd like it best if I could just change some `const string outputPath`.
As long as the script stays small and never changes between versions that should be fine.
The script only calls into the actual generator lib (that's present as a dll), right?
So if there's an update to the generator, its just the dll that gets replaced, and the little script (where I made my change to the output path) won't get replaced.

But that's just my opinion.

What do you think about that? What configuration way would you prefer?

> There's also a variety of options for making Ceras easily available to Unity users. Right now I'm...

> The System .dll files, while not present by default in the Unity editor, could already exist in the project 

I agree that that can be an issue. But I don't know how to handle this.
In fact, I think it is up to Unity to fix this somehow. 
They must have some package or dependency resolution thing.
Probably best if they'd have something like nuget and we could just tell it what dependencies ceras has (just like how `csproj` contains the nuget names).

**Comment by rikimaru0345** [comment]
Also, when you think the PR is ready to merge, add this commit to your PR as well https://github.com/rikimaru0345/Ceras/commit/099b28402d878d5112c23b49279841ee01f9240e and let me know.

**Comment by zvinless** [comment]
Merged it in!

I think it'd be fine to merge this in now; it already makes it simpler to generate AOT code for Unity. I'm just starting to experiment with creating a package manager package, which seems like it will affect how the generated code output path can be configured (among other things). Once I have something ready for that, I can create a new pull request.

**Pull request merged**
