### PR TITLE
General project structure cleanup, SourceLink Support and DependencyGroup cleanup

### PR DESCRIPTION
**Pull request by MeikTranel**
This PR will add SourceLink support as well as reduce dependencies for consumers using .NET Framework.
I also added basic configuration for development in VSCode and added some touches of project structure which really help provide some knobs to be turned on a "all tests" or "all sample projects" level - based on the new Directory.Build.props system.

### CODE REVIEW

**Comment by MeikTranel** [comment]
I made this compatible with your appveyor csproj patching mechanism, but i would really like to recommend controling version in your checked-in project configs. If you set the Version property in the root Directory.Build.props, all projects in subdirectories will gain this version variable. In my experience, CI-System driven versioning (especially in appveyor) can never hold up to manually bumping version variables directly in the repository. A good compromise would be setting Major.Minor.Patch (basically everything SemVer related) manually and patch a buildID and/or a commit hash through the CI System.

**Comment by rikimaru0345** [comment]
Hi, first of all thank you so much for this pr!
I just checked it out and I see that net472; was added. Since I don't have the sdk for 4.7.2 installed yet I wanted to ask if there's a reason for that.

>  In my experience, CI-System driven versioning (especially in appveyor) can never hold up to manually bumping version variables directly in the repository. A good compromise would be setting Major.Minor.Patch (basically everything SemVer related) manually and patch a buildID and/or a commit hash through the CI System.

Yes certainly.
Ceras follows semantic versioning (breaking.feature.build).
From what I've seen appveyor only auto increments and patches the build version, so that should be fine right? I still manually manage the first two (major / breaking version, and feature / nonbreaking improvement).


I'll try to merge this pr in the next hours! Thanks!

**Comment by MeikTranel** [comment]
> I just checked it out and I see that net472; 

For the current state of the code this is not important yet. Consider this. Let's say you want to use tuples from C# 7 somewhere inside your library. 
Tuples are really just syntactic sugar around the type System.ValueTuple.
System.ValueTuple is part of the .NET Framework 4.7.2 - it is not however part of .NET Framework 4.5, which is why the .NET / Visual Studio team deployed on their cheecky little hacks inside the compiler tooling. 
In the second you start to use one of these types in a TFM that doesn't deploy the required type, they automatically pull in the NuGet package "System.ValueTuple". They do the same thing with "Dynamic". If you use expose the Dynamic type somewhere in your library you automatically pull the "Microsoft.CSharp" package, which has all weird stuff required to support the type.

So now let's say someone uses your package in a csproj targeting .NET 4.8.X. The NuGet restore graph will then look at the best fit dependencygroup, which in your case would be .NET 4.5. It then sees that the .NET 4.5 dependencygroup pulls in System.ValueTuple and restores it right away. NuGet does not know that your TFM already exposes this type, which means that on build time it will put a System.ValueTuple.dll in your output directory, which you don't really need because the BCL already has that type hanging about.
By putting 4.7.2 as a TFM and thus adding it to the dependencygroups - the restore graph has a better fit for your 4.8 library, restores the 4.7.2 node and does in fact not put unused artifacts in your output directory.
Currently i use 4.7.2, because it has official 100% all .NET Standard 2.0 types and all required C# 7.X types.

**Comment by rikimaru0345** [comment]
Ohhh, that's good to know.
I heard that there's some sort of trickery going on with value tuple but didn't know what it was exactly, until now! Thanks again for explaining.
I'll install the 4.7.2 sdk asap and add the build target back into ceras' csproj.

**Comment by MeikTranel** [comment]
Again - no hurry. Currently you don't use these types - so as of right now, there is practically no difference between the net45 and the net472 dependency groups. 
It's just once you use one of these, that this will make a difference.

**Pull request merged**
