### PR TITLE
Unity Aot Hint

### PR DESCRIPTION
**Pull request by kononencheg**
Introduced
- namespace argument for codegen
- warning disabling
- unity aot hint

### CODE REVIEW

**Comment by kononencheg** [comment]
Also you should make some formatters public

**Comment by rikimaru0345** [comment]
Thanks for the PR!

> Also you should make some formatters public

Which ones?

**Comment by kononencheg** [comment]
KeyValuePairFormatter, Tuple formatters, etc.

**Comment by rikimaru0345** [comment]
> KeyValuePairFormatter, Tuple formatters, etc.

will do

**Pull request merged**
